src/api_gate/app/parselib/models.py
class Tender(object):
    link: str = ""
    number: str = ""
    name: str = ""
    price: str = ""
    int_price: int = 0

    def __str__(self) -> str:
        return f"""
                Tender:
                link: {self.link},
                number: {self.number},
                name: {self.name}
                price: {self.price}
                """

    def __repr__(self) -> str:
        return f"""
                Tender:
                link: {self.link},
                number: {self.number},
                name: {self.name}
                price: {self.price}
                """

    def cast_tender_price_to_int(self):
        import re
        self.int_price = int(re.sub(r"[^0-9]", "", self.price))
        self.int_price //= 100


class Customer(object):
    link: str = ""
    name: str = ""
    phone_number: str = ""
    inn: str = ""
    kpp: str = ""
    orgn: str = ""
    mail: str = ""
    site: str = ""

    def __str__(self) -> str:
        return f"""
                Customer:
                link: {self.link},
                name: {self.name},
                phone_number: {self.phone_number},
                inn: {self.inn}
                kpp: {self.kpp}
                orgn: {self.orgn}
                mail: {self.mail}
                site: {self.site}
                """

    def __repr__(self):
        return f"""
                        Customer:
                        link: {self.link},
                        name: {self.name},
                        phone_number: {self.phone_number},
                        inn: {self.inn}
                        kpp: {self.kpp}
                        orgn: {self.orgn}
                        mail: {self.mail}
                        site: {self.site}
                        """


class Supplier(Customer):
    price: str = ""
    int_price: int = 0
    count: int = 0
    tax: str = ""
    offer_descr: str = ""

    def cast_tender_price_to_int(self):
        import re
        self.int_price = int(re.sub(r"[^0-9]", "", self.price))
        self.int_price //= 100

    def __str__(self) -> str:
        return f"""
                   Supplier:
                   link: {self.link},
                   name: {self.name},
                   phone_number: {self.phone_number},
                   inn: {self.inn}
                   kpp: {self.kpp}
                   orgn: {self.orgn}
                   mail: {self.mail}
                   site: {self.site}
                   offer_descr: {self.offer_descr}
                   """

    def __repr__(self):
        return f"""
                   Supplier:
                   link: {self.link},
                   name: {self.name},
                   inn: {self.inn}
                   price: {self.price}
                   int_price: {self.int_price}
                   offer_descr: {self.offer_descr}
                   """

src/api_gate/app/src/models/mixins.py
from src import db


class DbMixin(object):
    def save(self) -> bool:
        try:
            db.session.add(self)
            db.session.commit()
            return True
        except Exception as e:
            db.session.rollback()
            return False

    def update(self):
        try:
            db.session.commit()
            return True
        except Exception as e:
            db.session.rollback()
            return False

    def delete(self):
        try:
            db.session.delete(self)
            db.session.commit()
            return True
        except Exception as e:
            db.session.rollback()
            return False

src/api_gate/app/src/models/user.py
from flask import jsonify

from app import db
from flask_login import UserMixin

from src.models.mixins import DbMixin


class User(DbMixin, UserMixin, db.Model):
    """
    Simple user model
    """

    __tablename__ = "users"

    # primary keys
    id = db.Column(db.Integer, primary_key=True)

    # model description
    username = db.Column(db.String(32), index=True)
    email = db.Column(db.String(32), )
    password_hash = db.Column(db.String(128))

    def __repr__(self) -> str:
        return f"User<id={self.id}, username={self.username}>"

    def __str__(self) -> str:
        return self.username

    def serialize(self) -> dict:
        return {
            "id": self.id,
            "username": self.username,
            "email": self.email
        }

src/api_gate/app/app.py
from flask_migrate import Migrate, upgrade
from src import create_app, db

app = create_app()
migrate = Migrate(app, db)

from src.models import user

src/api_gate/app/src/__init__.py
# flask imports
from flask_login import login_manager, LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask import Flask
# local imports
from src.utils.os_utils import get_env_variable

# init sqlalchemy stuff

db: SQLAlchemy = SQLAlchemy()
migrate: Migrate = Migrate()


def create_app() -> Flask:
    """
    Flask factory
    :return:
    """

    app: Flask = Flask(__name__)
    register_blueprints(app)
    # get postgres variables
    POSTGRES_URL: str = get_env_variable("POSTGRES_URL")
    POSTGRES_USER: str = get_env_variable("POSTGRES_USER")
    POSTGRES_DB: str = get_env_variable("POSTGRES_DB")

    DB_URL: str = f"postgresql+psycopg2://{POSTGRES_USER}@{POSTGRES_URL}/{POSTGRES_DB}"
    # create sqlalch instance

    app.config['SECRET_KEY'] = '9OLWxND4o83j4K4iuopO'
    app.config['SQLALCHEMY_DATABASE_URI'] = DB_URL
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)
    migrate.init_app(app, db)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login_get'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        from src.models.user import User
        return User.query.get(int(user_id))

    return app


def register_blueprints(app: Flask) -> None:
    from src.main import bp as MainBluePrint
    from src.auth import bp as AuthBluePrint
    app.register_blueprint(MainBluePrint)
    app.register_blueprint(AuthBluePrint)

src/api_gate/app/src/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from src.main import routes

src/api_gate/app/src/main/routes.py
from flask import render_template, request, redirect, url_for
from flask_login import login_required, current_user
from src.main import bp


@bp.route('/')
def index():
    return render_template('main/index.html')


@bp.route('/profile_get', methods=["GET"])
@login_required
def profile_get():
    context: dict = {
        'name': current_user.username,
    }
    return render_template('main/profile.html', context=context)


@bp.route('/_calculate_suppliers', methods=['POST'])
@login_required
def _calculate_suppliers():
    url = request.form.get('url')
    from parselib import parser
    context = parser.parse_tender_by_url(url)
    return render_template('main/result.html', context=context)


@bp.route('/calculate_result', methods=['GET'])
@login_required
def calculate_result():
    return request.args['context']

src/api_gate/app/src/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Умный помощник</title>

    <!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{{
  url_for('static', filename='jquery.js') }}">\x3C/script>')</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">Умный помощник</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <a href="{{ url_for('main.index') }}" class="p-2 text-dark">
            Стартовая страница
        </a>
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('main.profile_get') }}" class="p-2 text-dark">
            Умный помощник
        </a>
        {% endif %}
        {% if not current_user.is_authenticated %}
        <a href="{{ url_for('auth.login_get') }}" class="p-2 text-dark">
            Вход
        </a>
        <a class="btn btn-outline-primary" href="{{ url_for('auth.register_get') }}" class="p-2 text-dark">
            Регистрация
        </a>
        {% endif %}
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.logout') }}" class="p-2 text-dark">
            Выход
        </a>
        {% endif %}
    </nav>
</div>
    {% block content %}
    {% endblock %}
</body>
</html>

src/api_gate/app/src/templates/main/index.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="display: flex; justify-content: center; align-items: center; height: 100vh">
    <div class="col text-center">
        <h1>API GATE</h1>
        <p class="lead">SODA API GATE</p>
    </div>
</div>
{% endblock %}

src/api_gate/app/src/templates/main/profile.html
{% extends "base.html" %}

{% block content %}

<div class="container py-5">
        <form method="POST" action="/_calculate_suppliers">
            <fieldset>
                <div class="form-group has-error">
                    <input class="form-control input-lg" placeholder="URL-ссылка" type=text size=5 name=url>
                </div>
                <input class="btn btn-lg btn-primary btn-block" value="Проанализировать тендер" type="submit">
            </fieldset>
        </form>
</div>
{% endblock %}

src/api_gate/app/src/templates/main/result.html
{% extends "base.html" %}

{% block content %}

<div class="container py-5">
        <div class="row">
            <div class="card bg-danger card-cascade card-ecommerce wider shadow mb-5 ">
                <!--Card Body-->
                <div class="card-body card-body-cascade text-center">
                    <!--Card Title-->
                    <h4 class="card-title text-white"><strong>{{context["tender"].name}}</strong></h4> <!-- Card Description-->
                    <p class="card-text text-white" >{{context["tender"].number}}</p>
                    <p class="price text-white">{{context["tender"].price}}</p> <!-- Card Rating-->
                    <!--Card footer-->
                    <div class="card-footer text-white">
                        <p>{{context["tender"].link}}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="card bg-primary  card-cascade card-ecommerce wider shadow mb-5 ">
                <!--Card Body-->
                <div class="card-body card-body-cascade text-center">
                    <!--Card Title-->
                    <h4 class="card-title text-white"><strong><a href="">{{context["customer"].offer_descr}}</a></strong></h4> <!-- Card Description-->
                    <p class="card-text text-white">{{context["customer"].name}}</p>
                    <p class="price text-white">{{context["customer"].inn}}</p> <!-- Card Rating-->
                    <p class="price text-white">{{context["customer"].email}}</p> <!-- Card Rating-->
                    <p class="price text-white">{{context["customer"].phone}}</p> <!-- Card Rating-->
                    <!--Card footer-->
                    <div class="card-footer text-white">
                        <p>{{context["customer"].link}}</p>
                    </div>
                </div>
            </div>
        </div>
        {% for supplier in context['suppliers'] %}
        <div class="col-sm">
            <div class="card card-cascade card-ecommerce wider shadow mb-5 ">
                <!--Card Body-->
                <div class="card-body card-body-cascade text-center">
                    <!--Card Title-->
                    <h4 class="card-title"><strong><a href="">{{supplier.offer_descr}}</a></strong></h4> <!-- Card Description-->
                    <p class="card-text">{{supplier.name}}</p>
                    <p class="price">{{supplier.price}}</p> <!-- Card Rating-->
                    <!--Card footer-->
                    <div class="card-footer">
                        <p>{{supplier.link}}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}